dist: xenial

sudo: false

group: edge

language: php

env:
    global:
        - COMPOSER_UPDATE="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
        - COMPOSER_CONFIG="--global github-oauth.github.com b7244dc99194b22416d5ce46d511ce04049b23de"

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: "7.4"
        - php: "7.3"
        - php: "7.2"
        - php: "7.1"
        - php: "7.0"
        - php: "5.6"
        - php: "5.5"
          dist: trusty
        - php: "5.4"
          dist: trusty

install:
    - travis_retry composer self-update
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer config $COMPOSER_CONFIG
    - travis_retry composer update $COMPOSER_UPDATE

script:
    - vendor/bin/codecept run unit --coverage-xml
    - vendor/bin/coveralls
